Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
  Enabled: false

IndentationConsistency:
  Enabled: false

EmptyLinesAroundAccessModifier:
  Enabled: false
